version: '3.8'

networks:
  internal:
    driver: bridge

services:
  student-service:
    build: ./
    command: ./student-service
    restart: always
    networks:
      - internal
    ports:
      - 8000:8000
    depends_on:
      - kafka
      - db
      - cache
    environment:
      - DSN_STUDENTS=postgresql://root:secret@db:5432/students?sslmode=disable
      - DRIVER=postgres
      - HOST_REDIS=cache
      - PORT_REDIS=6379

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    networks:
      - internal
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=students
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    command: postgres -c 'shared_preload_libraries='
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d students"]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    restart: always
    image: redis:latest
    volumes: 
      - ./pkg/cache
    networks:
      - internal
    ports:
      - 6380:6379
    environment:
      - HOST_REDIS=cache
      - PORT_REDIS=6379
  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper
    expose:
    - "2181"
    ports:
    - "2181:2181"
    networks:
      - internal
  
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:5.2.2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - internal



